name: Tests
on: [pull_request]
jobs:
  integration-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: tests
        run: |
          go test -v ./...
